// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMD1NrpqAyI7lH4BSq8c-1rCSbmuZkGxQ',
    appId: '1:61134301045:web:c126ac03963b82fda8953c',
    messagingSenderId: '61134301045',
    projectId: 'shoesly-test',
    authDomain: 'shoesly-test.firebaseapp.com',
    databaseURL: 'https://shoesly-test-default-rtdb.firebaseio.com',
    storageBucket: 'shoesly-test.appspot.com',
    measurementId: 'G-LXKB7T7DRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDomMj8p0UHIiG0-mRE-iAOjNLUAf2Addw',
    appId: '1:61134301045:android:bb1fb061514441b2a8953c',
    messagingSenderId: '61134301045',
    projectId: 'shoesly-test',
    databaseURL: 'https://shoesly-test-default-rtdb.firebaseio.com',
    storageBucket: 'shoesly-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QaGiXsPL34mv3qciWeZQdOTUEW3njUU',
    appId: '1:61134301045:ios:9f3bfa987db81ad7a8953c',
    messagingSenderId: '61134301045',
    projectId: 'shoesly-test',
    databaseURL: 'https://shoesly-test-default-rtdb.firebaseio.com',
    storageBucket: 'shoesly-test.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2QaGiXsPL34mv3qciWeZQdOTUEW3njUU',
    appId: '1:61134301045:ios:9f3bfa987db81ad7a8953c',
    messagingSenderId: '61134301045',
    projectId: 'shoesly-test',
    databaseURL: 'https://shoesly-test-default-rtdb.firebaseio.com',
    storageBucket: 'shoesly-test.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMD1NrpqAyI7lH4BSq8c-1rCSbmuZkGxQ',
    appId: '1:61134301045:web:aa9400dbcb759b96a8953c',
    messagingSenderId: '61134301045',
    projectId: 'shoesly-test',
    authDomain: 'shoesly-test.firebaseapp.com',
    databaseURL: 'https://shoesly-test-default-rtdb.firebaseio.com',
    storageBucket: 'shoesly-test.appspot.com',
    measurementId: 'G-447Y88RSLP',
  );

}